name: taxi_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.1.7
  http: ^0.13.4
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  avatar_glow: ^2.0.2
  animated_text_kit: ^4.2.1
  flutter_onboard: ^2.0.0
  flutter_polyline_points: ^1.0.0
  fluttertoast: ^8.0.9
  geolocator: ^7.0.1
  shared_preferences: ^2.0.15
  flutter_google_places: ^0.3.0
  google_api_headers: ^1.3.0
  map_picker: ^0.0.3
  flutter_svg: ^1.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
 
  uses-material-design: true

  assets:
    - assets/
  

